spring:
  application:
    name: gateway
  config:
    import: optional:consul:${CONSUL_HOST:localhost}:8500
  cloud:
    consul:
      config:
        format: yaml
    gateway:
      discovery:
        locator:
          enabled: true